site_name: Drupal VM Documentation

repo_url: https://github.com/geerlingguy/drupal-vm
site_description: 'Drupal VM - A VM for local Drupal development, built with Vagrant + Ansible'
theme: readthedocs

extra_javascript:
  - js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Getting Started with DrupalVM with Docker:
    - Installation:
      - 'macOS': 'docker/getting-started/installation-macos.md'
      - 'Windows': 'docker/getting-started/installation-windows.md'
      - 'Linux': 'docker/getting-started/installation-linux.md'
  - Getting Started with DrupalVM with Vagrant:
    - Installation:
      - 'macOS': 'vagrant/getting-started/installation-macos.md'
      - 'Windows': 'vagrant/getting-started/installation-windows.md'
      - 'Linux': 'vagrant/getting-started/installation-linux.md'
    - 'Configuring Drupal VM': 'vagrant/getting-started/configure-drupalvm.md'
    - 'Syncing Folders': 'vagrant/getting-started/syncing-folders.md'
  - Building your codebase:
    - 'Using a local Drupal codebase': 'vagrant/deployment/local-codebase.md'
    - 'Using a composer package': 'vagrant/deployment/composer-package.md'
    - 'Using composer.json': 'vagrant/deployment/composer.md'
    - 'Using a Drush Make file': 'vagrant/deployment/drush-make.md'
    - 'Drupal VM as a Composer Dependency': 'vagrant/deployment/composer-dependency.md'
    - 'Deploying Drupal via Git': 'vagrant/deployment/git.md'
  - Basic configurations:
    - 'Using different base OSes': 'vagrant/configurations/base-os.md'
    - 'Using a different PHP version': 'vagrant/configurations/php.md'
    - Webservers:
      - 'Apache': 'vagrant/configurations/webservers-apache.md'
      - 'Nginx': 'vagrant/configurations/webservers-nginx.md'
    - Databases:
      - 'Connect to the MySQL Database': 'vagrant/configurations/databases-mysql.md'
      - 'Use MariaDB instead of MySQL': 'vagrant/configurations/databases-mariadb.md'
      - 'Use PostgreSQL instead of MySQL': 'vagrant/configurations/databases-postgresql.md'
  - Installed extras:
    - 'adminer (Database UI)': 'vagrant/extras/adminer.md'
    - 'blackfire (Profiling tool)': 'vagrant/extras/blackfire.md'
    - 'drupalconsole (Drupal CLI)': 'vagrant/extras/drupal-console.md'
    - 'drush (Drupal CLI)': 'vagrant/extras/drush.md'
    - 'elasticsearch (Search engine)': 'vagrant/extras/elasticsearch.md'
    - 'java': 'vagrant/extras/java.md'
    - 'mailhog (Mail catcher)': 'vagrant/extras/mailhog.md'
    - 'memcached (In-memory cache)': 'vagrant/extras/memcached.md'
    - 'newrelic (Performance monitoring)': 'vagrant/extras/newrelic.md'
    - 'nodejs': 'vagrant/extras/nodejs.md'
    - 'pimpmylog (Log viewer)': 'vagrant/extras/pimpmylog.md'
    - 'redis (In-memory database)': 'vagrant/extras/redis.md'
    - 'ruby': 'vagrant/extras/ruby.md'
    - 'selenium (BDD with Behat)': 'vagrant/extras/selenium.md'
    - 'solr (Search engine)': 'vagrant/extras/solr.md'
    - 'tideways (Profiling tool)': 'vagrant/extras/tideways.md'
    - 'upload-progress': 'vagrant/extras/upload-progress.md'
    - 'varnish (Caching reverse proxy)': 'vagrant/extras/varnish.md'
    - 'xdebug (Debugging tool)': 'vagrant/extras/xdebug.md'
    - 'xhprof (Profiling tool)': 'vagrant/extras/xhprof.md'
  - Extending Drupal VM:
    - 'Adding Vagrant plugins Vagrantfile.local': 'vagrant/extending/vagrantfile.md'
    - 'Passing on CLI arguments to ansible': 'vagrant/extending/ansible-args.md'
    - 'Pre- and Post-Provision Scripts': 'vagrant/extending/scripts.md'
  - Other Information:
    - 'Networking Notes': 'vagrant/other/networking.md'
    - 'Vagrant LXC provider': 'vagrant/other/vagrant-lxc.md'
    - 'Improving Performance': 'vagrant/other/performance.md'
    - 'Custom Vagrant Base Box': 'vagrant/other/custom-base-box.md'
    - 'BigPipe with Drupal VM': 'vagrant/other/bigpipe.md'
    - 'Drupal multisite': 'vagrant/deployment/multisite.md'
    - 'Drupal 6 Notes': 'vagrant/other/drupal-6.md'
    - 'Drupal VM Management Tools': 'vagrant/other/management-tools.md'
    - 'Emulating Acquia Cloud environment': 'vagrant/other/acquia.md'
    - 'Deploying to a production environment': 'vagrant/other/production.md'
    - 'Wordpress or other applications': 'vagrant/other/wordpress-other-applications.md'
